name: Tagpr
on:
  push:
    branches:
      - main

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: {}
    steps:
      - name: Fetch GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: token
        with:
          app-id: ${{ secrets.GH_APP_TAGPR_ID }}
          private-key: ${{ secrets.GH_APP_TAGPR_PKEY }}

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          token: ${{ steps.token.outputs.token }}

      - name: Tagpr
        id: tagpr
        uses: tapihdev/actionshub/Songmu/tagpr@main
        with:
          github-token: ${{ steps.token.outputs.token }}

      - name: Annotate major and minor tags
        if: steps.tagpr.outputs.tag != ''
        uses: tapihdev/tag-major-minor-semver@7b86820b4c4e796f6703c551c55ff8f42e165e3a # v1.0.5
        with:
          tag: ${{ steps.tagpr.outputs.tag }}
